### ISSUE TITLE
Version 1.2.01 Issue with PHP 7.1+

### ISSUE THREAD

**Issue by Sephster** [celtic-project/webpa-lti#1]
Hi Stephen. Following on from Bangor's reported issue of groups not syncing, I decided to take a look into this issue.

I believe there is a problem in the function `domnode_to_array()`.

```
private function domnode_to_array($node) {

    $output = (array) '';
    switch ($node->nodeType) {
      case XML_CDATA_SECTION_NODE:
      case XML_TEXT_NODE:
        $output = trim($node->textContent);
        break;
      case XML_ELEMENT_NODE:
        for ($i = 0; $i < $node->childNodes->length; $i++) {
          $child = $node->childNodes->item($i);
          $v = $this->domnode_to_array($child);
          if (isset($child->tagName)) {
            $t = $child->tagName;
            if (!isset($output[$t])) {
              $output[$t] = array();
            }
            $output[$t][] = $v;
          } else {
            $s = (string) $v;
            if (strlen($s) > 0) {
              $output = $s;
            }
          }
        }
        if (is_array($output)) {
          if ($node->attributes->length) {
            $a = array();
            foreach ($node->attributes as $attrName => $attrNode) {
              $a[$attrName] = (string) $attrNode->value;
            }
            $output['@attributes'] = $a;
          }
          foreach ($output as $t => $v) {
            if (is_array($v) && count($v)==1 && $t!='@attributes') {
              $output[$t] = $v[0];
            }
          }
        }
        break;
    }

    return $output;

  }
```

In the above example the code initialises `$output` as a blank string. Assuming we hit the case `XML_ELEMENT_NODE` we run the risk of running this section of code:

`$ouput[$t] = array()`

This is causing PHP 7.1+ to fail because from PHP 7.1, you cannot use string offset as an array. 

I believe this change isn't actually documented in the PHP changelog. I was able to fix this by either casting `$output` to an array or alternatively initialising it as an empty array instead of a blank string but I don't know enough about the code to understand whether this will have other consequences.

Would it be possible for you to take a second look at this to see if we can get a patch together for version 1.2.01 so it can be used by Bangor?

Thanks for your help and apologies in advance if I've made any mistakes with this.

**Comment by spvickers** [comment]
Thanks; I suspect this is the same fix as I have already committed to the LTI repository.

**Comment by spvickers** [comment]
I am currently testing the latest changes before making a formal release.

**Comment by Sephster** [comment]
Thanks Stephen. Will the release be an update to the 1.2.01 branch or will it only be included in the version 2 branch? Is it worth sharing this on the WebPA mailing list to make people aware a fix is in the work.

**Comment by spvickers** [comment]
I don't know which repository you are referring to; none of mine have a 1.2.01 branch.  The update in question will be part of version 3.1.1 of the LTI-PHP library.  I do not have sufficient information about the error reported by Bangor to know whether this fixes it; if it is the case I would have expected an error to be reported in the PHP error log file, but they did not mention this.

**Comment by spvickers** [comment]
Oh I now understand  - you are referring to version 1.2.01 of the connector.  This uses an old version of the PHP LTI library; I will think about whether to update this old library or just recommend using the new one.

**Comment by Sephster** [comment]
Yes, the version of the connector. Apologies I should have made that more clear. Is the latest LTI connector backwards compatible? If so, I think when the fix is applied to it, it should be fine for them to just upgrade as they are already using PHP 7.2 so it _should_ be supported.

Here is the error that was reported to myself by Bangor:

```
[Mon Apr 01 16:27:00.915111 2019] [php7:error] [pid 8754] [client 147.143.1.72:58804] PHP Fatal error:  Uncaught Error: Cannot use string offset as an array in /var/www/html/WebPA/mod/lti/lib/LTI_Tool_Provider.php:2296
```

I suggested casting the string to an array which appears to have fixed their immediate issue but wanted to reach out here as it likely needs more scrutiny
