### ISSUE TITLE
Bug with class WebPA_Tool

### ISSUE THREAD

**Issue by richeduni** [celtic-project/webpa-lti#2]
Hi Steven,

Andrew Millington said this is probably the best place to report bugs.

I have tried installing the lti tool with the latest version of webpa and get the following error:

`Use of undefined constant VERSION - assumed 'VERSION' (this will throw an Error in a future version of PHP) in /var/www/html/WebPA/src/mod/lti/tool.php on line 46`

**Comment by spvickers** [comment]
Are you trying to use the dynamic registration option from Moodle?  Try changing VERSION to APP__VERSION on the offending line.

**Comment by richeduni** [comment]
Will do. Thanks very much.

**Comment by spvickers** [comment]
Are you trying to use the dynamic registration option from Moodle to configure WebPA?

**Comment by Sephster** [comment]
Thanks Stephen for your help. No, we aren't planning on using dynamic reg and this will be linked in the first instance to Blackboard

**Comment by spvickers** [comment]
Thanks @Sephster.  I suspect this is just an error with the name of the version constant.  Let me know if that removes the notice, but note that I would not expect this to have any impact on making the connector work if you are not using the dynamic registration.  So please let me know if you are experiencing any issues other than an unwanted PHP notice in the log file.

**Comment by Sephster** [comment]
Will do. Thanks for your help

**Comment by spvickers** [comment]
Fix committed.
